repos:

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    exclude: Docker

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "^(tests/|examples/)"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.3.1
  hooks:
    - id: add-license-headers
      files: '(src|examples|tests|docker)/.*\.(py)|\.(proto)'
      args:
      - --start_year=2023

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.22.0
  hooks:
    - id: check-github-workflows