name: GitHub CI
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAIN_PYTHON_VERSION: '3.14'
  PACKAGE_NAME: 'ansys-sound-core'
  DOCUMENTATION_CNAME: 'sound.docs.pyansys.com'
  DOCUMENTATION_DPF_SOUND_TAG: 'latest' # DPF Sound image tag for doc building
  TEST_DPF_SOUND_MATRIX: '["25.2"]' # List of DPF Sound image tags for testing (quotes and double quotes are important!!)
  ANSRV_DPF_SOUND_REPO: ghcr.io/ansys/ansys-sound # Docker repository for DPF Sound
  ANSRV_DPF_SOUND_PORT: 6780 # Port to connect to DPF Sound Docker container
  ANSRV_DPF_SOUND_PORT_IN_CONTAINER: 50052 # Port inside DPF Sound Docker container
  DPF_SOUND_CONT_NAME: ansys-sound-core
  DPF_DEFAULT_GRPC_MODE: insecure

jobs:



# =================================================================================================
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# =================================================================================================

  # Retrieve test matrix from the environment variable, as env variables are not directly available
  # at matrix definition (in job testing-windows below).
  retrieve-test-matrix:
    name: "Retrieve test matrix of DPF Sound Docker images"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${TEST_DPF_SOUND_MATRIX}" >> $GITHUB_OUTPUT
        env:
          TEST_DPF_SOUND_MATRIX: ${{ env.TEST_DPF_SOUND_MATRIX }}

  testing-windows:
    name: "Testing"
    needs: [retrieve-test-matrix]
    runs-on: [self-hosted, Windows, pyansys-sound]
    permissions:
      contents: read  # Required to access test code
      packages: read  # Required to use the DPF Sound Docker image
    env:
      PYVISTA_OFF_SCREEN: true
      MPLBACKEND: Agg  # non-interactive mode ("headless backend") for matplotlib: no GUI is used when plotting
      UV_NO_CACHE: "true"
    strategy:
      fail-fast: false
      matrix:
        # This matrix contains tags of all DPF Sound Docker images to test against.
        # (see env.TEST_DPF_SOUND_MATRIX)
        docker-image: ${{ fromJson(needs.retrieve-test-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@c103a2ff45650d38cb71684b5dc6cdfeb9442c79 # v5.1.0
        with:
          pyvista: false

      - name: "Create Python venv"
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1

      - name: "Install packages for testing"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install --upgrade build wheel
          pip install .[tests]


      - name: "Testing"
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v

