name: GitHub CI
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAIN_PYTHON_VERSION: '3.14'
  PACKAGE_NAME: 'ansys-sound-core'
  DOCUMENTATION_CNAME: 'sound.docs.pyansys.com'
  DOCUMENTATION_DPF_SOUND_TAG: 'latest' # DPF Sound image tag for doc building
  TEST_DPF_SOUND_MATRIX: '["latest"]' # List of DPF Sound image tags for testing (quotes and double quotes are important!!)
  ANSRV_DPF_SOUND_REPO: ghcr.io/ansys/ansys-sound # Docker repository for DPF Sound
  ANSRV_DPF_SOUND_PORT: 6780 # Port to connect to DPF Sound Docker container
  ANSRV_DPF_SOUND_PORT_IN_CONTAINER: 50052 # Port inside DPF Sound Docker container
  DPF_SOUND_CONT_NAME: ansys-sound-core
  DPF_DEFAULT_GRPC_MODE: insecure

jobs:


# =================================================================================================
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# =================================================================================================

  # Retrieve test matrix from the environment variable, as env variables are not directly available
  # at matrix definition (in job testing-windows below).
  retrieve-test-matrix:
    name: "Retrieve test matrix of DPF Sound Docker images"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${TEST_DPF_SOUND_MATRIX}" >> $GITHUB_OUTPUT
        env:
          TEST_DPF_SOUND_MATRIX: ${{ env.TEST_DPF_SOUND_MATRIX }}

  testing-windows:
    name: "Testing"
    needs: [retrieve-test-matrix]
    runs-on: [self-hosted, Windows, pyansys-sound]
    permissions:
      contents: read  # Required to access test code
      packages: read  # Required to use the DPF Sound Docker image
    env:
      PYVISTA_OFF_SCREEN: true
      MPLBACKEND: Agg  # non-interactive mode ("headless backend") for matplotlib: no GUI is used when plotting
    strategy:
      fail-fast: false
      matrix:
        # This matrix contains tags of all DPF Sound Docker images to test against.
        # (see env.TEST_DPF_SOUND_MATRIX)
        docker-image: ${{ fromJson(needs.retrieve-test-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0 # v4.3
        with:
          pyvista: false

      - name: "Create Python venv"
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1

      - name: "Install packages for testing"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install --upgrade build wheel
          pip install .[tests]

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download DPF-Sound service container
        env:
          ANSRV_DPF_SOUND_IMAGE: "${{ env.ANSRV_DPF_SOUND_REPO }}:${{ matrix.docker-image }}"
        run: docker pull $env:ANSRV_DPF_SOUND_IMAGE

      - name: "Start DPF-Sound service and verify start"
        env:
          ANSRV_DPF_SOUND_IMAGE: "${{ env.ANSRV_DPF_SOUND_REPO }}:${{ matrix.docker-image }}"
          PORT_MAPPING: "${{ env.ANSRV_DPF_SOUND_PORT }}:${{ env.ANSRV_DPF_SOUND_PORT_IN_CONTAINER }}"
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
        run: |
          .\.venv\Scripts\Activate.ps1
          docker run -d --name $env:DPF_SOUND_CONT_NAME -e "DPF_DEFAULT_GRPC_MODE=insecure" -e "ANSYS_DPF_ACCEPT_LA=Y" -e "ANSYSLMD_LICENSE_FILE=1055@$env:LICENSE_SERVER" -p $env:PORT_MAPPING --dns '8.8.8.8' $env:ANSRV_DPF_SOUND_IMAGE
          python -c "from ansys.sound.core.server_helpers import validate_dpf_sound_connection; validate_dpf_sound_connection()"

      - name: "Testing"
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v

      - name: "Upload Coverage Results"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-html-${{ matrix.docker-image }}
          path: .cov/html
          retention-days: 7

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .cov/xml

      - name: "Stop the DPF-Sound service"
        if: always()
        run: |
          docker stop $env:DPF_SOUND_CONT_NAME
          docker logs $env:DPF_SOUND_CONT_NAME
          docker rm $env:DPF_SOUND_CONT_NAME

      - name: "Stop any remaining containers"
        if: always()
        run: |
          $dockerContainers = docker ps -a -q
          if (-not [string]::IsNullOrEmpty($dockerContainers)) {
              docker stop $dockerContainers
              docker rm $dockerContainers
          }

      - name: "Delete the Docker images (and untagged ones)"
        if: always()
        run: |
          docker system prune -f

# =================================================================================================
# =================================================================================================


  